# Generated by Django 3.2.23 on 2023-12-08 11:26

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_item',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='list_item',
            name='on_list',
        ),
        migrations.AddField(
            model_name='list_item',
            name='buyer_notes',
            field=models.TextField(default='Notes added by buyer'),
        ),
        migrations.AddField(
            model_name='list_item',
            name='creator_notes',
            field=models.TextField(default='Notes added by creator'),
        ),
        migrations.AddField(
            model_name='list_item',
            name='date_bought',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='list_item',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='list_item',
            name='quantity_bought',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='list_item',
            name='quantity_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='list_item',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_who_created_shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('default_quantity', models.IntegerField()),
                ('default_unit', models.CharField(max_length=10)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_who_created_product', to=settings.AUTH_USER_MODEL)),
                ('default_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_where_to_buy', to='family_shopper.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_who_created_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='list_item',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_of_list_item', to='family_shopper.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_item',
            name='shop_bought',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shop_where_item_bought', to='family_shopper.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_item',
            name='shopper_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_who_bought_item', to='family_shopper.product'),
            preserve_default=False,
        ),
    ]
