# Generated by Django 3.2.23 on 2023-12-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_shopper', '0002_auto_20231214_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='list_item',
            old_name='shopper_id',
            new_name='shopper',
        ),
    ]
