# Generated by Django 3.2.23 on 2023-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_shopper', '0003_auto_20231219_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
